var searchData=
[
  ['l2_5fnorm_76',['l2_norm',['../classLinearAlgebra_1_1SharedMPI_1_1Vector.html#a30f9abae38525fcbd6fe165f27aa2e26',1,'LinearAlgebra::SharedMPI::Vector']]],
  ['local_5felement_77',['local_element',['../classLinearAlgebra_1_1SharedMPI_1_1Vector.html#ab67d94baf2f4998123011d63610c90b3',1,'LinearAlgebra::SharedMPI::Vector::local_element(const size_type local_index)'],['../classLinearAlgebra_1_1SharedMPI_1_1Vector.html#acb0fdc457bdcec25297dd5c10d2a915b',1,'LinearAlgebra::SharedMPI::Vector::local_element(const size_type local_index) const']]],
  ['local_5fsize_78',['local_size',['../classLinearAlgebra_1_1SharedMPI_1_1Vector.html#adb9858ccf939ac709a1bbf6da0ee51d4',1,'LinearAlgebra::SharedMPI::Vector::local_size()'],['../classhyperdeal_1_1internal_1_1MatrixFreeFunctions_1_1Partitioner.html#a610560a29f9be942f22cf105511bbe33',1,'hyperdeal::internal::MatrixFreeFunctions::Partitioner::local_size()']]],
  ['loop_79',['loop',['../classhyperdeal_1_1TimeLoop.html#a82c02a047a15d85e4d77d9c70e9482bf',1,'hyperdeal::TimeLoop::loop()'],['../classhyperdeal_1_1MatrixFree.html#a755e13b9b3e13de90309faf8f6ff74a4',1,'hyperdeal::MatrixFree::loop(const std::function&lt; void(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID)&gt; &amp;cell_operation, const std::function&lt; void(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID)&gt; &amp;face_operation, const std::function&lt; void(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID)&gt; &amp;boundary_operation, OutVector &amp;dst, const InVector &amp;src, const DataAccessOnFaces dst_vector_face_access=DataAccessOnFaces::unspecified, const DataAccessOnFaces src_vector_face_access=DataAccessOnFaces::unspecified, Timers *timers=nullptr) const'],['../classhyperdeal_1_1MatrixFree.html#a40b9f52f041f09201109f80205baf4b1',1,'hyperdeal::MatrixFree::loop(void(CLASS::*cell_operation)(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID), void(CLASS::*face_operation)(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID), void(CLASS::*boundary_operation)(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID), CLASS *owning_class, OutVector &amp;dst, const InVector &amp;src, const DataAccessOnFaces dst_vector_face_access=DataAccessOnFaces::unspecified, const DataAccessOnFaces src_vector_face_access=DataAccessOnFaces::unspecified, Timers *timers=nullptr) const']]],
  ['loop_5fcell_5fcentric_80',['loop_cell_centric',['../classhyperdeal_1_1MatrixFree.html#a6cc7840dd917dd59d992d02489f6395b',1,'hyperdeal::MatrixFree::loop_cell_centric(const std::function&lt; void(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID)&gt; &amp;cell_operation, OutVector &amp;dst, const InVector &amp;src, const DataAccessOnFaces src_vector_face_access=DataAccessOnFaces::unspecified, Timers *timers=nullptr) const'],['../classhyperdeal_1_1MatrixFree.html#a2cb86a4d1822d0f6ea77ea47e8cbc6c3',1,'hyperdeal::MatrixFree::loop_cell_centric(void(CLASS::*cell_operation)(const MatrixFree &amp;, OutVector &amp;, const InVector &amp;, const ID), CLASS *owning_class, OutVector &amp;dst, const InVector &amp;src, const DataAccessOnFaces src_vector_face_access=DataAccessOnFaces::unspecified, Timers *timers=nullptr) const']]],
  ['lowstoragerungekuttaintegrator_81',['LowStorageRungeKuttaIntegrator',['../classhyperdeal_1_1LowStorageRungeKuttaIntegrator.html',1,'hyperdeal::LowStorageRungeKuttaIntegrator&lt; Number, VectorType &gt;'],['../classhyperdeal_1_1LowStorageRungeKuttaIntegrator.html#afd5497392807cf193c8d9c28aa786cd6',1,'hyperdeal::LowStorageRungeKuttaIntegrator::LowStorageRungeKuttaIntegrator()']]],
  ['lowstoragerungekuttaintegratorparamters_82',['LowStorageRungeKuttaIntegratorParamters',['../structhyperdeal_1_1LowStorageRungeKuttaIntegratorParamters.html',1,'hyperdeal']]]
];
