name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
         docker pull dealii/dealii:master-focal
         command="git clone https://github.com/${{ github.repository }} && \
                  cd hyperdeal && git fetch origin ${{ github.ref }} && \
                  git checkout FETCH_HEAD && \
                  git --no-pager  log | head -n50 && \
                  mkdir build && \ 
                  cd build && \
                  cmake .. && \
                  make -j2 && \
                  ctest -V";
         
         echo $command
         docker run -t dealii/dealii:master-focal /bin/sh -c "$command";

